# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       libnl
Summary:    Convenience library for kernel netlink sockets
Version:    3.2.9
Release:    1
Group:      System/Libraries
License:    LGPL
URL:        http://www.infradead.org/~tgr/libnl/
Source0:    http://www.infradead.org/~tgr/libnl/files/libnl-%{version}.tar.gz
Source100:  libnl.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  flex
BuildRequires:  byacc
BuildRequires:  bison


%description
This package contains a convenience library to simplify
using the Linux kernel's netlink sockets interface for
network manipulation



%package devel
Summary:    Libraries and headers for using libnl
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains various headers for using libnl

%package cli
Summary:    Command line interface utils for libnl
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description cli
This package contains various libnl3 utils and additional
libraries on which they depend.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# Makefile junk in the docs. Error by rpmlint.
find doc/ -name 'Makefile*' -exec rm '{}' \;
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig






%post cli -p /sbin/ldconfig

%postun cli -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc COPYING
%{_libdir}/libnl-3.so.*
%{_libdir}/libnl-genl-3.so.*
%{_libdir}/libnl-nf-3.so.*
%{_libdir}/libnl-route-3.so.*
%config(noreplace) %{_sysconfdir}/*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%doc doc/*
%{_includedir}/libnl3/netlink/
%dir %{_includedir}/libnl3/
%{_libdir}/*.so
%{_libdir}/pkgconfig/*.pc
# << files devel

%files cli
%defattr(-,root,root,-)
# >> files cli
%doc COPYING
%{_libdir}/libnl-cli*.so.*
%{_libdir}/libnl/
%{_sbindir}/*
%{_mandir}/man8/*
# << files cli

